# Generated by Django 5.1.4 on 2025-01-08 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cvImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
