# Generated by Django 5.1.4 on 2025-01-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculations', '0002_cvimage_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
